# Generated by Django 4.0.5 on 2022-08-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0002_categorysubscribers_category_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_type',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', help_text='post type', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(help_text='category name', through='NewsPortal.PostCategory', to='NewsPortal.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='post title', max_length=128),
        ),
    ]
