# Generated by Django 4.0.5 on 2022-08-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0003_alter_post_category_type_alter_post_postcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, verbose_name='post title'),
        ),
    ]
